---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centos7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    # image: quay.io/centos/centos:stream8
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy