---
- name: Dependency
  hosts: all
  tasks:
    - name: "Install Clickhouse"
      include_role:
        name: "ansible-clickhouse"
  post_tasks:
    - name: Create table
      ansible.builtin.command: "clickhouse-client -q 'CREATE TABLE IF NOT EXISTS logs.local_log
        (file String, hostname String, message String, timestamp DateTime) Engine=Log;'"
      register: create_table
      failed_when: create_table.rc != 0 and create_table.rc !=57
      changed_when: create_table.rc == 0
      when: not ansible_check_mode
